### ISSUE TITLE
New boot files don't show up in editor within core PAWs without exiting/re-entering editor

### ISSUE THREAD

**Issue by mgalyean** [KSP-KOS/KOS#2838]
I tried and failed to find a dupe of this but I'd be surprised if it isn't a dupe.  Given how messy exiting the editor can be when one has detached subassemblies lying about it would be a big win if when any time the PAW for a core is brought up in the editor and the boot file selector clicked that a check is done for new files in Script/boot and they are added to the available boot file options. I'm not trying to get this in as a last minute add to the upcoming release, timing is coincidental.  It is completely understandable that it wouldn't be in the upcoming release if ever

**Comment by Dunbaratu** [comment]
Not sure if it's a duplicate but it's not exactly a bug - perhaps a feature request?

**Comment by nuggreat** [comment]
While not a bad idea to have some way to force I reload I would prefer if it was a button some where as apposed to happening every time you touch the GUI as that would cause a massive amount of unnecessary disk activity.  And in at least my case I am still on spinning disks for KSP which would mean a slow down in the editor due to the wait.

**Comment by Dunbaratu** [comment]
I'm trying to find if the API has some sort of hook like "on PAW opened" that I can check into and go "If the PAW in question contains a kOS module then reload the disk directory".  But I'm not seeing it if it's there.

Perhaps I could just add a button just under the boot file selector labeled "Reread Boot Folder". - click the button when you think the list of options is stale?

**Comment by mgalyean** [comment]
A separate button is fine.  Maybe not even in the PAW, but in something that pops up when clicking the kOS menu icon in the toolbar would be perfectly suitable.  And probably more appropriate really given the apparent quixotic nature of PAW changes on KSP's end

**Comment by Dunbaratu** [comment]
I'm re-opening this issue because it turns out it has this problem:

While the boot file list *is* reloaded when you hit the button, that reloading has no effect on kOS parts that you already pulled from the parts bin and attached to the vessel.  It only affects new kOS parts you add after that.

For the button to truly work fully, it needs to tell any existing kOS PartModules in the scene that the list has changed and they need to re-read it.

**Comment by darthgently** [comment]
This bug was previously reported and addressed by the placement of a "re-read boot directory" button in the kOS pop-up in editor.  I recall there is one caveat that only new cores placed on the craft will have the new boot files available so to see the new boot files on cores already on the craft you have to delete them and do them again.  But at least you don't have to exit and re-enter the editor

**Comment by angeld23** [comment]
> This bug was previously reported and addressed by the placement of a "re-read boot directory" button in the kOS pop-up in editor. I recall there is one caveat that only new cores placed on the craft will have the new boot files available so to see the new boot files on cores already on the craft you have to delete them and do them again. But at least you don't have to exit and re-enter the editor

I'm aware, I'm saying that not only do existing CPUs still not get refreshed, but also at some point _newly placed CPUs_ had the latest boot files, _regardless of if the re-read button was ever pressed_. This means that the only remaining function of the button is no longer necessary, which was just to make a point that the button is basically "dead weight" until it gets fixed.

**Comment by darthgently** [comment]
My bad, I skimmed and missed.  Carry on wayward sons

**Comment by nuggreat** [comment]
In some quick testing on my system the button refreshed the boot file lists of one of the already placed cores.  It didn't refresh all of them but it did partly work.

**Comment by darthgently** [comment]
Interesting.  Was the PAW open or closed on the one that worked?

**Comment by angeld23** [comment]
> In some quick testing on my system the button refreshed the boot file lists of one of the already placed cores.  It didn't refresh all of them but it did partly work.

That's more confusing than if it just didn't work at all :P
